### ISSUE TITLE
expect(json["name"]).to eq "Second Sample Project"に対してno implicit conversion of String into Integerのエラー発生

### ISSUE THREAD

**Issue by Tohru-f** [JunichiIto/everydayrails-rspec-jp-2024#13]
訳著で勉強させて頂いています。

日本語版の最新版テキストでp126のコードをVSCode(Mac)で実行した所、エラーが発生したので下記の通りお知らせします。

原著のリポジトリ、日本語版のリポジトリで掲載されているissueを見ても同様の内容は見つけられなかったのでissueを発行いたします。

既に対処済みでしたらご容赦ください。

## 発生したエラー
Projects API
  loads a project (FAILED - 1)

Failures:

  1) Projects API loads a project
     Failure/Error: expect(json["name"]).to eq "Second Sample Project"
     
     TypeError:
       no implicit conversion of String into Integer
     /# ./spec/requests/projects_api_spec.rb:36:in `[]'
     /# ./spec/requests/projects_api_spec.rb:36:in `block (2 levels) in <top (required)>'

Finished in 0.07714 seconds (files took 0.81057 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/requests/projects_api_spec.rb:11 # Projects API loads a project

## 期待した結果
下記のようにテストのパス
Projects API
  GET /projects_apis
    loads a project

Finished in 0.07528 seconds (files took 0.84046 seconds to load)
1 example, 0 failures

## 再現手順

1, p126のコードをエディタに入力
2, bundle exec rspec spec/requests/projects_api_spec.rb で実行

------実際に入力したコード-----
require 'rails_helper'

RSpec.describe "Projects API", type: :request do
  describe "GET /projects_apis" do

    # 1件のプロジェクトを読み出すこと
    it 'loads a project' do
      user = FactoryBot.create(:user)
      FactoryBot.create(:project,
        name: "Sample Project")
      FactoryBot.create(:project,
        name: "Second Sample Project",
        owner: user)

      get api_projects_path, params: {
        user_email: user.email,
        user_token: user.authentication_token
      }

      expect(response).to have_http_status(:success)
      json = JSON.parse(response.body)
      expect(json.length).to eq 1
      project_id = json[0]["id"]

      get api_projects_path(project_id), params: {
        user_email: user.email,
        user_token: user.authentication_token
      }

      expect(response).to have_http_status(:success)
      json = JSON.parse(response.body)
      expect(json["name"]).to eq "Second Sample Project"
    end
  end
end
-------------------------

## 解決する為にとった対策
最終行の
expect(json["name"]).to eq "Second Sample Project"
に対して、27行目のproject_id = json[0]["id"]と同様にjsonはハッシュの配列と捉えて
expect(json[0]["name"]).to eq "Second Sample Project"と変更しました。
※jsonの後ろに[0]を追記

これにより期待する結果であるテストをパスすることができました。

## 実行環境
- 端末：Mac M2チップ
- OS：Sequoia Ver.15.1.1
- Ruby；3.2.1
- RSpec：3.13

## 補足資料
[[No implicit conversion of String into Integer (TypeError)?](https://stackoverflow.com/questions/20790499/no-implicit-conversion-of-string-into-integer-typeerror)]
[no implicit conversion of String into Integer の対処について【Ruby】](https://qiita.com/Coconew5/items/304b7da019b8727112ed)

最後まで読んで頂きありがとうございます。

**Comment by JunichiIto** [comment]
ご報告ありがとうございます。
こちら、手が空いたタイミングで確認しますので、すいませんがしばらくお待ちください 🙏

**Comment by JunichiIto** [comment]
遅くなってすいません。こちら確認しました。
結論からいうと、 @Tohru-f さんが入力されたコード（2つめのget）に間違いがあるようです。

```ruby 
  # 誤 → projects （複数形）なので index を表示しようとしている
  get api_projects_path(project_id), params: {
    user_email: user.email,
    user_token: user.authentication_token
  }

  # 正 → project （単数形）なので show を表示する
  get api_project_path(project_id), params: {
    user_email: user.email,
    user_token: user.authentication_token
  }
```

正しいコードを入力すると、書籍のコードのままでも動作するはずです。
（`s`があるかないかだけの違いだけなので紛らわしいところではありますが・・・）

また、書籍のコードはこのGitHubリポジトリでも公開しています。
たとえば今回のコードならこちらにあります。
https://github.com/JunichiIto/everydayrails-rspec-jp-2024/blob/main/spec/requests/projects_api_spec.rb#L4-L28

もし動かないコードに遭遇したら、このリポジトリのコードを動かしてみて、挙動にあるのかないのか、もし違いがあるならコード上の何が違うのかを調査してもらうと自力で解決しやすくなるかもしれません。

以上、よろしくお願いします 😃

**Comment by Tohru-f** [comment]
ご確認ありがとうございます。

お忙しい中で時間を割いて頂きありがとうございます。

私のタイポが原因でコード修正ではなく、別の方法で対処できてしまっていたようです。

お手間をとらせて申し訳ありませんでした。
