### ISSUE TITLE
Microsoft Defender Antivirusがウィルスを検出します

### ISSUE THREAD

**Issue by kyontanyk** [JunichiIto/everydayrails-rspec-jp-2024#6]
Ruby/Rails初心者です。
本mainブランチのDownload Zipを試みたところ、Windows11のWindowsセキュリティ（Microsoft Defender Antivirus)が「ウィルスを検出しました」と表示しダウンロードされませんでした。app/views/layouts/application.html.erbに対し、Trojan:Script/Wacatac.B!mlを検出したとの事。
重大度は最大である「重大」とされ、詳細には「このプログラムは危険であり、攻撃者からのコマンドを実行します。」とあります。
この検出を回避させることは難しいでしょうか？

なお、上記セキュリティソフトのバージョンは下記です。（頻繁に更新されるウイルス対策のバージョンは2024/3/11時点で最新です）
Windows セキュリティ アプリケーションのバージョン: 1000.25873.0.9001
Windows セキュリティ サービス バージョン: 1.0.2306.10002-0
マルウェア対策クライアントのバージョン: 4.18.24010.12
エンジンのバージョン: 1.1.24020.9
ウイルス対策のバージョン: 1.407.291.0
スパイウェア対策のバージョン: 1.407.291.0

一方、別のWindows11 PCにはESET Internet Security 17.0.16.0を導入していますが、そちらでは特に異常検出なく正常ダウンロードできました。

**Comment by JunichiIto** [comment]
ご報告どうもありがとうございます。
まさかのウイルス検知ですか。おそらく誤検知だと思うのですが、ちょっと気持ち悪いですね。

なんとなくの予想ですが、以下の行が怪しまれてるような気がします。
https://github.com/JunichiIto/everydayrails-rspec-jp-2024/blob/main/app/views/layouts/application.html.erb#L9-L11

Macユーザーなので確認や対応策を考えるのが難しいのですが、たとえばzipのダウンロードではなく、git cloneでコードをダウンロードしてみるとどうなりますか？

```
git clone https://github.com/JunichiIto/everydayrails-rspec-jp-2024.git
```

**Comment by kyontanyk** [comment]
2004/3/13今朝、改めてWindows Update後、本mainブランチのDownload Zipを試みたところ、異常検出なく正常ダウンロードできるようになってました。Microsoft Defender Antivirusに不具合があったのだと思われます。お騒がせしました。
新たなセキュリティソフトのバージョンは下記です。

Windows セキュリティ アプリケーションのバージョン: 1000.25873.0.9001
Windows セキュリティ サービス バージョン: 1.0.2306.10002-0
マルウェア対策クライアントのバージョン: 4.18.24020.7
エンジンのバージョン: 1.1.24020.9
ウイルス対策のバージョン: 1.407.383.0
スパイウェア対策のバージョン: 1.407.383.0

**Comment by JunichiIto** [comment]
それなら良かったです！安心しました 😄
